### ISSUE TITLE
400 Error

### ISSUE THREAD

**Issue by Entkenntnis** [serlo/serlo.org-database-layer#80] opened 2021-02-28 08:55 UTC
When I visit https://de.serlo.org/70696, I get a very strange redirect:

https://de.serlo.org/rs%00%00%00%00%00%00/70696/proteine-aufbau-und-funktion

**Comment by kulla** [comment] 2021-03-01 16:50
CF uses the alias it gets from the api:

![2021-03-01-174348_990x237_scrot](https://user-images.githubusercontent.com/1327215/109529271-dc61d380-7ab5-11eb-9c7f-989b2d1f1fa5.png)

When I look at the URL I guess it's another example of the weird bug we have. `%00` is the [null character](https://en.wikipedia.org/wiki/Null_character) and this character should never occur in a string. Since the api only forwards the alias it gets from the database layer I guess the bug is in the database layer.

I added an empty edit by visiting https://de.serlo.org/entity/repository/add-revision/70696 in hope the new edit will overwrite the cache entry for this alias in the api (since malformed cache entries can be fixed by refetching them from the database layer) but it did not helped...

**Comment by kulla** [comment] 2021-03-01 17:01
Okay, I just made an edit with a real change and now the api response is right:

![2021-03-01-175946_975x232_scrot](https://user-images.githubusercontent.com/1327215/109531296-00beaf80-7ab8-11eb-9b7b-3a770d00dfc8.png)

@dal Can you check whether https://de.serlo.org/70696 works for you?

**Comment by kulla** [comment] 2021-03-01 17:06
Okay, there might be a bug with deleting a cache key in CF. I need to check this in an hour again... after the cache key expired in CF it should work again...

**Comment by kulla** [comment] 2021-03-01 18:30
The redirect of de.serlo.org/70696 is fixed now (I guess due to my edit and the following new setting of the cache entry in the api). As I said, I guess this is another example for the weird bug @inyono is looking for to fix in the database layer.

The weird part for me is that the pathname `/rs%00%00%00%00%00%00/70696/proteine-aufbau-und-funktion` has the right structure. In case of a malfunction I would assume the whole pathname to be not usable. Here only the subject prefix is malformed. It seems to me, that only https://github.com/serlo/serlo.org-database-layer/blob/0f45e0111e103e9c0ea5c0dcc999dd5794e48c40/src/uuid/model/entity/mod.rs#L183 returned a malformed value. Might it be, that here a value in the memory is read which is not set properly before?

**Comment by kulla** [comment] 2021-03-01 18:30
@inyono Feel free to close this issue. I am not sure whether this issue is helpful or not...

**Comment by inyono** [comment] 2021-03-05 15:43
Closing because not reproducible.

**Closed by inyono** 2021-03-05 15:43 UTC
Labels: bug
